module.exports = {
  START_ALL: 1,
  START_GET: 2,
  START_TREATMENT: 3,

  TREATMENT_STAMPS: 1,
  TREATMENT_JUTSUS: 2,
  TREATMENT_CHARACTERS: 3,

  TREATMENT_CHARACTERS_DESCRIPTION: 1,

  TREATMENT_JUTSUS_DESCRIPTION: 1,
  TREATMENT_JUTSUS_RANK: 2,

  GET_CHARACTERS: 1,
  GET_JUTSUS: 2,

  GET_CHARACTERS_ALL: 1,
  GET_CHARACTERS_IMAGE: 2
}
